# Generated by Django 4.2.16 on 2026-09-22 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('level', models.CharField(choices=[('STATE', 'State'), ('DISTRICT', 'District'), ('BLOCK', 'Block'), ('VILLAGE', 'Village'), ('CUSTOM', 'Custom')], db_index=True, max_length=16)),
                ('geometry_geojson', models.TextField(blank=True, null=True)),
                ('area_sqkm', models.FloatField(blank=True, null=True)),
                ('centroid_lat', models.FloatField(blank=True, null=True)),
                ('centroid_lon', models.FloatField(blank=True, null=True)),
                ('bbox_minx', models.FloatField(blank=True, null=True)),
                ('bbox_miny', models.FloatField(blank=True, null=True)),
                ('bbox_maxx', models.FloatField(blank=True, null=True)),
                ('bbox_maxy', models.FloatField(blank=True, null=True)),
                ('is_demo', models.BooleanField(default=False, help_text='True if this is DEMO DATA, not official government data.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='administration.administrativeunit')),
            ],
            options={
                'verbose_name': 'Administrative Unit',
                'verbose_name_plural': 'Administrative Units',
                'db_table': 'administrative_unit',
                'ordering': ['level', 'name'],
            },
        ),
    ]
