# Generated by Django 4.2.16 on 2026-09-22 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_type', models.CharField(choices=[('FLOOD', 'Flood'), ('EARTHQUAKE', 'Earthquake'), ('CYCLONE', 'Cyclone'), ('LANDSLIDE', 'Landslide'), ('DROUGHT', 'Drought'), ('FOREST_FIRE', 'Forest Fire')], max_length=32)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=64)),
                ('default_weight', models.FloatField(default=5.0, help_text='Default weight on 0–10 scale.')),
                ('min_weight', models.FloatField(default=0.0)),
                ('max_weight', models.FloatField(default=10.0)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hazard Indicator',
                'db_table': 'hazard_indicator',
                'ordering': ['hazard_type', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HazardLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hazard_type', models.CharField(choices=[('FLOOD', 'Flood'), ('EARTHQUAKE', 'Earthquake'), ('CYCLONE', 'Cyclone'), ('LANDSLIDE', 'Landslide'), ('DROUGHT', 'Drought'), ('FOREST_FIRE', 'Forest Fire')], max_length=32)),
                ('geometry_type', models.CharField(choices=[('POLYGON', 'Polygon'), ('POINT', 'Point'), ('LINE', 'Line / Linestring')], max_length=32)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('vintage', models.CharField(blank=True, help_text='Data vintage year or period.', max_length=32)),
                ('crs', models.CharField(default='EPSG:4326', help_text='Coordinate Reference System.', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('geometry_geojson', models.TextField(blank=True, null=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hazard Layer',
                'db_table': 'hazard_layer',
            },
        ),
        migrations.CreateModel(
            name='HazardType',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False, help_text='True if this hazard is fully implemented in the prototype.')),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('color', models.CharField(blank=True, default='#3B82F6', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hazard Type',
                'db_table': 'hazard_type',
            },
        ),
        migrations.CreateModel(
            name='IndicatorWeightageRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. 'Low', 'Moderate', 'High'", max_length=64)),
                ('range_min', models.FloatField(help_text='Inclusive lower bound of value range.')),
                ('range_max', models.FloatField(blank=True, help_text='Exclusive upper bound. Null = no upper bound.', null=True)),
                ('score', models.FloatField(help_text='Score assigned to this range (0–10 scale).')),
                ('description', models.TextField(blank=True)),
                ('is_prototype_threshold', models.BooleanField(default=True, help_text='True = prototype/configurable threshold, False = official documented threshold.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weightage_rules', to='hazards.hazardindicator')),
            ],
            options={
                'verbose_name': 'Indicator Weightage Rule',
                'db_table': 'indicator_weightage_rule',
                'ordering': ['indicator', 'range_min'],
            },
        ),
        migrations.CreateModel(
            name='HazardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_type', models.CharField(choices=[('FLOOD', 'Flood'), ('EARTHQUAKE', 'Earthquake'), ('CYCLONE', 'Cyclone'), ('LANDSLIDE', 'Landslide'), ('DROUGHT', 'Drought'), ('FOREST_FIRE', 'Forest Fire')], db_index=True, max_length=32)),
                ('event_date', models.DateField(db_index=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('magnitude', models.FloatField(blank=True, help_text='Magnitude or intensity (hazard-specific unit).', null=True)),
                ('loss', models.FloatField(blank=True, help_text='Estimated loss (INR crore).', null=True)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('geometry_geojson', models.TextField(blank=True, null=True)),
                ('is_demo', models.BooleanField(default=False, help_text='True if this is DEMO DATA, not official historical data.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administrative_unit', models.ForeignKey(blank=True, help_text='Pre-assigned admin unit (set by GIS processing).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hazard_events', to='administration.administrativeunit')),
            ],
            options={
                'verbose_name': 'Hazard Event',
                'verbose_name_plural': 'Hazard Events',
                'db_table': 'hazard_event',
                'ordering': ['-event_date'],
            },
        ),
    ]
