# Generated by Django 4.2.16 on 2026-09-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hazardindicator',
            options={'ordering': ['module_type', 'hazard_type', 'order', 'name'], 'verbose_name': 'Hazard Indicator'},
        ),
        migrations.AlterModelOptions(
            name='hazardtype',
            options={'ordering': ['name'], 'verbose_name': 'Hazard Type'},
        ),
        migrations.AddField(
            model_name='hazardindicator',
            name='module_type',
            field=models.CharField(choices=[('HAZARD', 'Hazard'), ('VULNERABILITY', 'Vulnerability'), ('EXPOSURE', 'Exposure')], db_index=True, default='HAZARD', help_text='HVRA framework module this indicator belongs to.', max_length=16),
        ),
        migrations.AlterField(
            model_name='hazardindicator',
            name='hazard_type',
            field=models.CharField(blank=True, choices=[('FLOOD', 'Flood'), ('EARTHQUAKE', 'Earthquake'), ('CYCLONE', 'Cyclone'), ('LANDSLIDE', 'Landslide'), ('DROUGHT', 'Drought'), ('FOREST_FIRE', 'Forest Fire')], max_length=32),
        ),
    ]
