# Generated by Django 4.2.16 on 2026-09-25 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('hazards', '0002_alter_hazardindicator_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(choices=[('HAZARD', 'Hazard'), ('VULNERABILITY', 'Vulnerability'), ('EXPOSURE', 'Exposure'), ('COMPOSITE_RISK', 'Composite Risk')], db_index=True, default='HAZARD', max_length=16)),
                ('hazard_type', models.CharField(blank=True, choices=[('FLOOD', 'Flood'), ('EARTHQUAKE', 'Earthquake'), ('CYCLONE', 'Cyclone'), ('LANDSLIDE', 'Landslide'), ('DROUGHT', 'Drought'), ('FOREST_FIRE', 'Forest Fire')], help_text='Optional hazard filter (e.g. only FLOOD recommendations).', max_length=32)),
                ('classification', models.CharField(blank=True, help_text='Optional class filter (NH/LH/MH/HH or VERY_HIGH/HIGH/MODERATE/LOW). Blank = applies to all classes.', max_length=16)),
                ('text', models.TextField()),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=16)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_demo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recommendation',
                'db_table': 'recommendation',
                'ordering': ['module_type', 'display_order', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='ClimateContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_type', models.CharField(blank=True, choices=[('FLOOD', 'Flood'), ('EARTHQUAKE', 'Earthquake'), ('CYCLONE', 'Cyclone'), ('LANDSLIDE', 'Landslide'), ('DROUGHT', 'Drought'), ('FOREST_FIRE', 'Forest Fire')], help_text='Hazard the statement relates to. Blank = general/state-wide.', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('statement', models.TextField(help_text='Narrative climate context (trends, projections, drivers).')),
                ('source', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('vintage', models.CharField(blank=True, max_length=32)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_demo', models.BooleanField(default=True, help_text='True = DEMO DATA (prototype content, not a real climate assessment).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(blank=True, help_text='Optional region (district) scope. Blank = state-wide.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='climate_contexts', to='administration.administrativeunit')),
            ],
            options={
                'verbose_name': 'Climate Context',
                'verbose_name_plural': 'Climate Context Entries',
                'db_table': 'climate_context',
                'ordering': ['hazard_type', 'display_order'],
            },
        ),
    ]
