# Generated by Django 4.2.16 on 2026-09-25 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PLATFORM_ADMIN', 'Platform Admin'), ('STATE_OFFICIAL', 'State Official'), ('DISTRICT_OFFICIAL', 'District Official'), ('ANALYST', 'Analyst'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=24)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(blank=True, help_text='Default district for DISTRICT_OFFICIAL users.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officer_profiles', to='administration.administrativeunit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profile',
            },
        ),
    ]
