# Generated by Django 4.2.16 on 2026-09-25 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.ForeignKey(blank=True, help_text='Territory state for STATE_OFFICIAL users (blank = all states).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_officer_profiles', to='administration.administrativeunit'),
        ),
    ]
