# Generated by Django 4.2.16 on 2026-09-22 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datasets', '0001_initial'),
        ('administration', '0001_initial'),
        ('hazards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('hazard_type', models.CharField(db_index=True, max_length=32)),
                ('administrative_level', models.CharField(default='BLOCK', help_text='The level at which assessment is performed (BLOCK, VILLAGE, etc.).', max_length=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('normalization_method', models.CharField(default='min_max', max_length=32)),
                ('classification_method', models.CharField(default='threshold', max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='DRAFT', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('configuration_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of all settings used, stored for auditability.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='datasets.datasource')),
                ('district', models.ForeignKey(limit_choices_to={'level': 'DISTRICT'}, on_delete=django.db.models.deletion.PROTECT, related_name='district_assessments', to='administration.administrativeunit')),
                ('state', models.ForeignKey(limit_choices_to={'level': 'STATE'}, on_delete=django.db.models.deletion.PROTECT, related_name='state_assessments', to='administration.administrativeunit')),
            ],
            options={
                'verbose_name': 'Assessment',
                'db_table': 'assessment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_value', models.FloatField(blank=True, null=True)),
                ('normalized_value', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('weighted_score', models.FloatField(blank=True, null=True)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('classification', models.CharField(blank=True, choices=[('NH', 'No Hazard'), ('LH', 'Low Hazard'), ('MH', 'Medium Hazard'), ('HH', 'High Hazard')], max_length=4)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administrative_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_results', to='administration.administrativeunit')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessments.assessment')),
                ('indicator', models.ForeignKey(blank=True, help_text='NULL = composite/summary result row.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='hazards.hazardindicator')),
            ],
            options={
                'verbose_name': 'Assessment Result',
                'db_table': 'assessment_result',
                'ordering': ['administrative_unit__name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(help_text='User-configured weight for this indicator (0–10).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='assessments.assessment')),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datasets.datasource')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_uses', to='hazards.hazardindicator')),
            ],
            options={
                'verbose_name': 'Assessment Indicator',
                'db_table': 'assessment_indicator',
                'unique_together': {('assessment', 'indicator')},
            },
        ),
    ]
