# Generated by Django 4.2.16 on 2026-09-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Stores raw calculation components (total_area, flood_prone_percentage, etc.) on the summary row.'),
        ),
    ]
