# Generated by Django 4.2.16 on 2026-09-24 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments', '0002_assessmentresult_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('administrative_level', models.CharField(default='BLOCK', help_text='The level at which the risk assessment is performed.', max_length=16)),
                ('formula', models.CharField(choices=[('MULTIPLICATIVE', 'Multiplicative (Risk = H × V × E)'), ('ADDITIVE', 'Weighted Sum (Risk = wH·H + wV·V + wE·E)')], default='MULTIPLICATIVE', max_length=16)),
                ('hazard_weight', models.FloatField(default=1.0, help_text='User-adjustable weight for the Hazard component (0–10).')),
                ('vulnerability_weight', models.FloatField(default=1.0, help_text='User-adjustable weight for the Vulnerability component (0–10).')),
                ('exposure_weight', models.FloatField(default=1.0, help_text='User-adjustable weight for the Exposure component (0–10).')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='DRAFT', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('configuration_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(limit_choices_to={'level': 'DISTRICT'}, on_delete=django.db.models.deletion.PROTECT, related_name='district_risk_assessments', to='administration.administrativeunit')),
            ],
            options={
                'verbose_name': 'Risk Assessment',
                'db_table': 'risk_assessment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='module_type',
            field=models.CharField(choices=[('HAZARD', 'Hazard'), ('VULNERABILITY', 'Vulnerability'), ('EXPOSURE', 'Exposure')], db_index=True, default='HAZARD', max_length=16),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='hazard_type',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='RiskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_score', models.FloatField(blank=True, null=True)),
                ('vulnerability_score', models.FloatField(blank=True, null=True)),
                ('exposure_score', models.FloatField(blank=True, null=True)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('risk_class', models.CharField(blank=True, choices=[('VERY_HIGH', 'Very High Risk'), ('HIGH', 'High Risk'), ('MODERATE', 'Moderate Risk'), ('LOW', 'Low Risk')], max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administrative_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_results', to='administration.administrativeunit')),
                ('risk_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessments.riskassessment')),
            ],
            options={
                'verbose_name': 'Risk Result',
                'db_table': 'risk_result',
                'ordering': ['administrative_unit__name'],
            },
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='exposure_assessment',
            field=models.ForeignKey(blank=True, help_text='Completed Exposure assessment (Module 3).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_exposure_risk', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='hazard_assessment',
            field=models.ForeignKey(blank=True, help_text='Completed Hazard assessment (Module 1).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_hazard_risk', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='state',
            field=models.ForeignKey(limit_choices_to={'level': 'STATE'}, on_delete=django.db.models.deletion.PROTECT, related_name='state_risk_assessments', to='administration.administrativeunit'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='vulnerability_assessment',
            field=models.ForeignKey(blank=True, help_text='Completed Vulnerability assessment (Module 2).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_vulnerability_risk', to='assessments.assessment'),
        ),
    ]
