# Generated by Django 4.2.16 on 2026-09-25 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments', '0003_riskassessment_assessment_module_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('SUBMITTED', 'Submitted for Review'), ('APPROVED', 'Approved / Endorsed'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Disaster Management Task Force review status.', max_length=16),
        ),
        migrations.AddField(
            model_name='assessment',
            name='review_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='reviewer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assessment',
            name='reviewer_org',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assessment',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('SUBMITTED', 'Submitted for Review'), ('APPROVED', 'Approved / Endorsed'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Disaster Management Task Force review status.', max_length=16),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='review_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='reviewer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='reviewer_org',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SavedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('module_type', models.CharField(choices=[('HAZARD', 'Hazard'), ('VULNERABILITY', 'Vulnerability'), ('EXPOSURE', 'Exposure'), ('COMPOSITE_RISK', 'Composite Risk')], db_index=True, max_length=16)),
                ('hazard_type', models.CharField(blank=True, max_length=32)),
                ('administrative_level', models.CharField(default='BLOCK', max_length=16)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('share_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_queries', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(limit_choices_to={'level': 'DISTRICT'}, on_delete=django.db.models.deletion.PROTECT, related_name='saved_queries_district', to='administration.administrativeunit')),
                ('state', models.ForeignKey(limit_choices_to={'level': 'STATE'}, on_delete=django.db.models.deletion.PROTECT, related_name='saved_queries_state', to='administration.administrativeunit')),
            ],
            options={
                'verbose_name': 'Saved Query',
                'db_table': 'saved_query',
                'ordering': ['-created_at'],
            },
        ),
    ]
